### PR TITLE
 added support for Comments

### LINKED ISSUE #11: Support comments for RRSets
PowerDNS supports comments on RRSets, but python-powerdns does not. It is simply not available in the RRSet constructor.

This should only be a small change to the RRSet Constructor because currently you can hack it in this way:

```
rrset = powerdns.RRSet(name="dummy", rtype="AAAA", records=["2001:db8::42"])
rrset["comments"] = [{"account": "test", "modifized_at":1622463776, "content": "yolo"}]
my_zone.create_records([rrset])
```

This is not very nice to use.
A solution would be to expand the RRSet constructor to allow comments and extend the `__str__` and `__repr__` methods.

I will prepare a Pull Request for that.

Comments in the PowerDNS Docs: https://doc.powerdns.com/md/httpapi/api_spec/#zone95collection

### PR DESCRIPTION
**Pull request by 991jo**
This closes #11

Opening this as a new PR because the old one was based on my master branch.

### CODE REVIEW

**Comment by 991jo** [comment]
Any chance to get some progress on this one?

**Comment by outini** [comment]
Hello,

Sorry for the delai :/
Yes, I will handle the MR review at lunchtime today. I'll let you know if
everything's ok.

Regards,

**Comment by 991jo** [comment]
No problem, I am fine with that. You dont have to do it today. Take your time. I was just worried, that this was forgotten.

**Comment by outini** [comment]
hello,

Thank you for the PR, it works like a charm, I'll merge it.

However, as I do not use the typing notation support from python 3.5 (https://docs.python.org/3/library/typing.html) I will remove it if next commit to keep consistency in the project coding style. As the Python runtime does not enforce anything on this, I prefer to keep a clear and compact coding style, and rely on Sphinx notation in doc strings to describe functions and variables.

Thank you again for this,

Have a nice day

**Pull request merged**
